#!/bin/sh

# Ensure the celery worker is stopped.
set +e
pid="$(cat "${OPENSHIFT_DATA_DIR}/run/celery.pid" 2>/dev/null)"
if [[ -n "${pid}" ]]; then
  kill "${pid}"
fi
rm -f "${OPENSHIFT_DATA_DIR}/run/celery.pid"
exit 0
